In [235]:
import pandas as pd
import numpy as np

In [236]:
df = pd.read_csv("../data/food_prediction_cleaned_data.csv")

In [237]:
df.head(2)

,Unnamed: 0,name,image_url,description,cuisine,course,diet,prep_time,ingredients,instructions,contain_milk,contain_curd,onion/garlic
0,0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,Thayir Semiya or Curd Vermicelli is a quick di...,Indian,Lunch,Vegetarian,35,"1/2 cup semiya (vermicelli) , roasted 1 cup ...","To begin making the Thayir Semiya recipe, firs...",0,1,0
1,1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,Chettinad Style Kara Kuzhambu Recipe with Pot...,South Indian Recipes,Lunch,Vegetarian,75,for ground masala 1/4 teaspoon methi seeds (fe...,To begin making the Chettinad Style Kara Kuzha...,0,0,1

In [238]:
columns_to_remove = ['Unnamed: 0', 'prep_time', 'contain_milk', 'contain_curd', 'onion/garlic']  
df.drop(columns=columns_to_remove, axis=1, inplace=True)

In [239]:
df.head(2)

,name,image_url,description,cuisine,course,diet,ingredients,instructions
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,Thayir Semiya or Curd Vermicelli is a quick di...,Indian,Lunch,Vegetarian,"1/2 cup semiya (vermicelli) , roasted 1 cup ...","To begin making the Thayir Semiya recipe, firs..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,Chettinad Style Kara Kuzhambu Recipe with Pot...,South Indian Recipes,Lunch,Vegetarian,for ground masala 1/4 teaspoon methi seeds (fe...,To begin making the Chettinad Style Kara Kuzha...

In [240]:
df.iloc[2]['instructions']

'To prepare Goan Chana Ros recipe, soak the white peas in water for 8 hours or overnight.Pressure cook the white peas along with chopped onions by adding 1 cup water for 4-5 whistles or till boiled. Let the pressure from pressure cooker get released on its own.Dry roast coriander seeds, dry red chilies and cloves together, till nice aroma gets emitted from coriander seeds. Let it cool down.Take a Mixer and add grated coconut, tamarind and dry roasted spices. Add 1/2 to 3/4 cup water and grind this into a smooth paste.Now take a Kadai and add the ground gravy to it. Switch on the gas and keep it on low flame.After 5 minutes, add the boiled white peas along with onion to the gravy and mix well. If the gravy is thick, add remaining water from the pressure cooker and mix.Add salt to taste and simmer for 10 minutes before switching off the gas.Serve Goan Chana Ros recipe with\xa0hot rice,\xa0Kelyachyo Fodi (banana)'

In [241]:
df['cuisine'].value_counts().reset_index()#['count']

                      cuisine  count
0        North Indian Recipes    813
1                      Indian    802
2        South Indian Recipes    625
3             Bengali Recipes    163
4                  Tamil Nadu    158
5              Kerala Recipes    158
6       Maharashtrian Recipes    136
7                   Karnataka    132
8           Gujarati Recipes﻿    124
9                  Rajasthani    116
10                     Andhra    116
11                    Punjabi     85
12               Goan Recipes     83
13                  Chettinad     67
14                   Kashmiri     58
15                Mangalorean     44
16                     Awadhi     36
17              Parsi Recipes     35
18                     Sindhi     32
19                    Mughlai     31
20                     Konkan     30
21              Oriya Recipes     28
22                 Hyderabadi     27
23                   Assamese     26
24                     Bihari     22
25   North East India Recipes     20
26                   Himachal     17
27                     Fusion     16
28                      Coorg     15
29          Coastal Karnataka     14
30            North Karnataka     14
31                      Udupi     12
32                    Malabar     11
33              Uttar Pradesh     11
34                  Pakistani     11
35                   Lucknowi      9
36            South Karnataka      8
37                    Malvani      8
38                 Sri Lankan      8
39             Middle Eastern      6
40                      Asian      6
41               Indo Chinese      5
42                   Nepalese      5
43                   Nagaland      5
44                Continental      5
45  Uttarakhand-North Kumaon       4
46                  Kongunadu      3
47                    Haryana      3
48                  Jharkhand      2
49                    Chinese      2
50                       Thai      1
51                       Arab      1
52                    Sichuan      1
53                     Afghan      1

In [242]:
cuisines_to_drop  = ['Thai','Chinese','Chinese','Sichuan','Afghan', 'Arab']

In [243]:
df = df[~df['cuisine'].isin(cuisines_to_drop)]

In [244]:
df['cuisine'].value_counts()

cuisine
North Indian Recipes         813
Indian                       802
South Indian Recipes         625
Bengali Recipes              163
Kerala Recipes               158
Tamil Nadu                   158
Maharashtrian Recipes        136
Karnataka                    132
Gujarati Recipes﻿            124
Rajasthani                   116
Andhra                       116
Punjabi                       85
Goan Recipes                  83
Chettinad                     67
Kashmiri                      58
Mangalorean                   44
Awadhi                        36
Parsi Recipes                 35
Sindhi                        32
Mughlai                       31
Konkan                        30
Oriya Recipes                 28
Hyderabadi                    27
Assamese                      26
Bihari                        22
North East India Recipes      20
Himachal                      17
Fusion                        16
Coorg                         15
North Karnataka               14
Coastal Karnataka             14
Udupi                         12
Uttar Pradesh                 11
Pakistani                     11
Malabar                       11
Lucknowi                       9
Malvani                        8
Sri Lankan                     8
South Karnataka                8
Asian                          6
Middle Eastern                 6
Continental                    5
Nagaland                       5
Nepalese                       5
Indo Chinese                   5
Uttarakhand-North Kumaon       4
Haryana                        3
Kongunadu                      3
Jharkhand                      2
Name: count, dtype: int64

In [245]:
df.head(2)

,name,image_url,description,cuisine,course,diet,ingredients,instructions
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,Thayir Semiya or Curd Vermicelli is a quick di...,Indian,Lunch,Vegetarian,"1/2 cup semiya (vermicelli) , roasted 1 cup ...","To begin making the Thayir Semiya recipe, firs..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,Chettinad Style Kara Kuzhambu Recipe with Pot...,South Indian Recipes,Lunch,Vegetarian,for ground masala 1/4 teaspoon methi seeds (fe...,To begin making the Chettinad Style Kara Kuzha...

In [246]:
df.iloc[1]['ingredients']

'for ground masala 1/4 teaspoon methi seeds (fenugreek seeds)  2 teaspoons coriander (dhania) seeds  1 teaspoon fennel seeds (saunf)  2 dry red chillies  1/4 cup fresh coconut , grated for the kuzhambu 1/2 cup pearl onions (sambar onions) , quartered  5 cloves garlic , finely chopped  2 tomatoes , finely chopped  2 potatoes (aloo) , cut into medium sized pieces  2 brinjal (baingan / eggplant) , cut into wedges  1 tablespoon jaggery  1 cup tamarind water  1 teaspoon sambar powder for seasoning 1 teaspoon gingelly oil  1/2 teaspoon mustard seeds (rai/ kadugu)  2 sprig curry leaves '

In [247]:
import re

paragraph = df.iloc[3]['ingredients']
# Extract the words within parentheses from the paragraph
words_in_brackets = re.findall(r'\((.*?)\)', paragraph)

# Print the extracted words
for word in words_in_brackets:
    print(word.strip())

haldi
jeera
dhania
maida

In [248]:
import re

def convert(obj):
    l = []
    # Extract the words within parentheses from the paragraph
    words_in_brackets = re.findall(r'\((.*?)\)', obj)

    # Print the extracted words
    for word in words_in_brackets:
        l.append((word.strip()))
    return l

In [249]:
df['itesms'] = df['ingredients'].apply(convert)

In [250]:
df['items'] = [str(a).replace("/",'')for a in df['itesms']]

In [251]:
df.head(1)

,name,image_url,description,cuisine,course,diet,ingredients,instructions,itesms,items
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,Thayir Semiya or Curd Vermicelli is a quick di...,Indian,Lunch,Vegetarian,"1/2 cup semiya (vermicelli) , roasted 1 cup ...","To begin making the Thayir Semiya recipe, firs...","[vermicelli, dahi / yogurt, rai/ kadugu, split...","['vermicelli', 'dahi yogurt', 'rai kadugu', '..."

In [252]:
df.drop(['itesms'], axis=1,inplace=True)

In [253]:
df.drop(['ingredients','instructions','description'], axis=1,inplace=True)

In [254]:
df.head(5)

,name,image_url,cuisine,course,diet,items
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,Indian,Lunch,Vegetarian,"['vermicelli', 'dahi yogurt', 'rai kadugu', '..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,South Indian Recipes,Lunch,Vegetarian,"['fenugreek seeds', 'dhania', 'saunf', 'sambar..."
2,Goan Chana Ros Recipe (White Peas Curry),https://www.archanaskitchen.com/images/archana...,Goan Recipes,Lunch,Vegetarian,"['vatana', 'dhania', 'laung', 'haldi']"
3,Minced Meat And Egg Croquettes Recipe,https://www.archanaskitchen.com/images/archana...,North Indian Recipes,Appetizer,Non Vegeterian,"['haldi', 'jeera', 'dhania', 'maida']"
4,Thekera Tenga Recipe,https://www.archanaskitchen.com/images/archana...,Assamese,Dinner,Vegetarian,"['aloo', 'haldi', 'dhania']"

In [255]:
df['diet'] = [a.replace(" ", '') for a in df['diet']]

In [256]:
df['diet'].value_counts()

diet
Vegetarian                  2829
HighProteinVegetarian        514
NonVegeterian                238
DiabeticFriendly             235
HighProteinNonVegetarian     138
Eggetarian                    95
NoOnionNoGarlic(Sattvic)      60
GlutenFree                    35
Vegan                         21
Name: count, dtype: int64

In [257]:
df['diet'] = [a.replace("(Sattvic)", '') for a in df['diet']]

In [258]:
df['diet'] = [a.lower() for a in df['diet']]

In [259]:
df['diet'].value_counts()

diet
vegetarian                  2829
highproteinvegetarian        514
nonvegeterian                238
diabeticfriendly             235
highproteinnonvegetarian     138
eggetarian                    95
noonionnogarlic               60
glutenfree                    35
vegan                         21
Name: count, dtype: int64

In [260]:
df.head(1)

,name,image_url,cuisine,course,diet,items
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,Indian,Lunch,vegetarian,"['vermicelli', 'dahi yogurt', 'rai kadugu', '..."

In [261]:
df['course'] = [a.lower() for a in df['course']]
df['cuisine'] = [a.lower() for a in df['cuisine']]

In [262]:
df['cuisine'] = [a.replace("recipes","") for a in df['cuisine']]

In [263]:
df['cuisine'] = [a.replace(" ","") for a in df['cuisine']]
df['course'] = [a.replace(" ","") for a in df['course']]

In [264]:
df['items'] = [a.replace(" ","") for a in df['items']]

In [270]:
df['cuisine'] = df['cuisine'].apply(lambda x: x.split())
df['course'] = df['course'].apply(lambda x: x.split())
df['diet'] = df['diet'].apply(lambda x: x.split())

In [271]:
df.head(8)

,name,image_url,cuisine,course,diet,items
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,[indian],[lunch],[vegetarian],"['vermicelli','dahiyogurt','raikadugu','split'..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,[southindian],[lunch],[vegetarian],"['fenugreekseeds','dhania','saunf','sambaronio..."
2,Goan Chana Ros Recipe (White Peas Curry),https://www.archanaskitchen.com/images/archana...,[goan],[lunch],[vegetarian],"['vatana','dhania','laung','haldi']"
3,Minced Meat And Egg Croquettes Recipe,https://www.archanaskitchen.com/images/archana...,[northindian],[appetizer],[nonvegeterian],"['haldi','jeera','dhania','maida']"
4,Thekera Tenga Recipe,https://www.archanaskitchen.com/images/archana...,[assamese],[dinner],[vegetarian],"['aloo','haldi','dhania']"
5,Spicy Cabbage Rice Recipe (South Indian Style ...,https://www.archanaskitchen.com/images/archana...,[indian],[lunch],[vegetarian],"['jeera','pattagobimuttaikose','haldi','dhania']"
6,Mullangi Poriyal Recipe,https://www.archanaskitchen.com/images/archana...,[tamilnadu],[dinner],[diabeticfriendly],"['radish','cleaned,peeled&chopped','haldi','dh..."
7,Karwar Style Surana Bhaji Recipe - Hot and Sou...,https://www.archanaskitchen.com/images/archana...,[karnataka],[sidedish],[vegetarian],"['suransenairatalu','raikadugu','fenugreekseed..."

In [272]:
df['tags'] = df['cuisine'] + df['course'] + df['diet']

In [275]:
df.drop(['cuisine','course','diet'], axis=1,inplace=True)

In [310]:
df['items'] = [re.sub(r'[''^\w\s]', ' ', word) for word in df['items']]

In [329]:
string = df['items']
df['items_re'] = ' '.join(str(string).split())

In [332]:
df.drop(['items_re'], axis=1,inplace=True)

In [359]:
df['items_ag'] = df['items'].str.replace('\s{3,}', ', ', regex=True)

In [345]:
df['items_re'] = df['items'].str.replace('\s+', ', ', regex=True)

In [378]:
df.head(9)

,name,image_url,items,tags,items_ag,it
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,vermicelli dahiyogurt raikadugu split ...,"[indian, lunch, vegetarian]","vermicelli, dahiyogurt, raikadugu, split, hi...","vermicelli, dahiyogurt, raikadugu, split, hi..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,fenugreekseeds dhania saunf sambaronio...,"[southindian, lunch, vegetarian]","fenugreekseeds, dhania, saunf, sambaronions,...","fenugreekseeds, dhania, saunf, sambaronions,..."
2,Goan Chana Ros Recipe (White Peas Curry),https://www.archanaskitchen.com/images/archana...,vatana dhania laung haldi,"[goan, lunch, vegetarian]","vatana, dhania, laung, haldi","vatana, dhania, laung, haldi"
3,Minced Meat And Egg Croquettes Recipe,https://www.archanaskitchen.com/images/archana...,haldi jeera dhania maida,"[northindian, appetizer, nonvegeterian]","haldi, jeera, dhania, maida","haldi, jeera, dhania, maida"
4,Thekera Tenga Recipe,https://www.archanaskitchen.com/images/archana...,aloo haldi dhania,"[assamese, dinner, vegetarian]","aloo, haldi, dhania","aloo, haldi, dhania"
5,Spicy Cabbage Rice Recipe (South Indian Style ...,https://www.archanaskitchen.com/images/archana...,jeera pattagobimuttaikose haldi dhania,"[indian, lunch, vegetarian]","jeera, pattagobimuttaikose, haldi, dhania","jeera, pattagobimuttaikose, haldi, dhania"
6,Mullangi Poriyal Recipe,https://www.archanaskitchen.com/images/archana...,radish cleaned peeled chopped haldi dh...,"[tamilnadu, dinner, diabeticfriendly]","radish, cleaned peeled chopped, haldi, dhani...","radish, cleaned peeled chopped, haldi, dhani..."
7,Karwar Style Surana Bhaji Recipe - Hot and Sou...,https://www.archanaskitchen.com/images/archana...,suransenairatalu raikadugu fenugreekseed...,"[karnataka, sidedish, vegetarian]","suransenairatalu, raikadugu, fenugreekseeds,...","suransenairatalu, raikadugu, fenugreekseeds,..."
8,Malvani Fish Curry Recipe - Delicious And Spic...,https://www.archanaskitchen.com/images/archana...,raikadugu haldi jeera dhania dhania ...,"[malvani, lunch, highproteinnonvegetarian]","raikadugu, haldi, jeera, dhania, dhania, jee...","raikadugu, haldi, jeera, dhania, dhania, jee..."

In [362]:
df.drop(['items_re'], axis=1,inplace=True)

In [381]:
df['it'] = df['items_ag'].tolist()

In [379]:
df['it'] = df['it'].apply(lambda x: x.split())

In [383]:
df.head(2)

,name,image_url,items,tags,items_ag,it
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,vermicelli dahiyogurt raikadugu split ...,"[indian, lunch, vegetarian]","vermicelli, dahiyogurt, raikadugu, split, hi...","vermicelli, dahiyogurt, raikadugu, split, hi..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,fenugreekseeds dhania saunf sambaronio...,"[southindian, lunch, vegetarian]","fenugreekseeds, dhania, saunf, sambaronions,...","fenugreekseeds, dhania, saunf, sambaronions,..."

In [388]:
df['t'] = df['tags'].apply(lambda x:" ".join(x))

In [389]:
df.head(2)

,name,image_url,items,tags,items_ag,it,t
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,vermicelli dahiyogurt raikadugu split ...,"[indian, lunch, vegetarian]","vermicelli, dahiyogurt, raikadugu, split, hi...","vermicelli, dahiyogurt, raikadugu, split, hi...",indian lunch vegetarian
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,fenugreekseeds dhania saunf sambaronio...,"[southindian, lunch, vegetarian]","fenugreekseeds, dhania, saunf, sambaronions,...","fenugreekseeds, dhania, saunf, sambaronions,...",southindian lunch vegetarian

In [391]:
df['main_tag'] = df['t'] +  df['it']

In [396]:
df.drop(['items_ag','items','tags','it','t'], axis=1,inplace=True)

In [397]:
df.head(2)

,name,image_url,main_tag
0,Thayir Semiya Recipe (Curd Semiya),https://www.archanaskitchen.com/images/archana...,"indian lunch vegetarian vermicelli, dahiyogur..."
1,Chettinad Style Kara Kuzhambu Recipe with Pota...,https://www.archanaskitchen.com/images/archana...,"southindian lunch vegetarian fenugreekseeds, ..."